vanderloo_2022SDE.pdf: vanderloo_2022SDE.tex vanderloo.bib
	pdflatex vanderloo_2022SDE.tex
	bibtex vanderloo_2022SDE
	pdflatex vanderloo_2022SDE.tex
	pdflatex vanderloo_2022SDE.tex
	xdg-open vanderloo_2022SDE.pdf
	
